name: appwrite
version: 0.4.0-dev.4
description: Appwrite is an open-source self-hosted backend server that abstract and simplify complex and repetitive development tasks behind a very simple REST API
homepage: https://appwrite.io
repository: https://github.com/appwrite/sdk-for-flutter
issue_tracker: https://github.com/appwrite/sdk-generator/issues
documentation: https://appwrite.io/support
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cookie_jar: ^3.0.0-beta2
  dio: ^4.0.0-prev3
  dio_cookie_manager: ^2.0.0-prev1
  flutter_web_auth: ^0.2.4
  meta: ^1.3.0
  package_info_plus: ^1.0.0
  path_provider: ^2.0.1
  universal_html: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
