name: appwrite
version: 0.0.1
description: Repo short description goes here
homepage: https://example.com
repository: https://github.com/repoowner/reponame
issue_tracker: https://github.com/appwrite/sdk-generator/issues
documentation: https://appwrite.io/support
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cookie_jar: ^1.0.1
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  flutter_web_auth: ^0.2.4
  meta: ^1.1.8
  package_info_plus: ^0.6.3
  path_provider: ^1.6.14
  universal_html: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
